name: admin
description: A new Flutter project.


version: 3.1.0+11

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  cloud_firestore:
  firebase_core: ^2.7.0
  intl: ^0.17.0
  provider: ^6.0.0
  shared_preferences: ^2.0.18
  cached_network_image: ^3.1.0
  url_launcher: ^6.1.10
  line_icons: ^2.0.1
  fluttertoast: ^8.2.1
  google_fonts: ^4.0.3
  firebase_auth: ^4.2.9
  url_strategy: ^0.2.0
  image_picker: ^0.8.6+3
  firebase_storage: ^11.0.14
  dotted_border: ^2.0.0+3
  rounded_loading_button: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    
    - assets/images/



    

